first commit
yufuworks/chat-space pull request #17
Opened 2019-04-23 12:36 UTC by yufuworks

2019-04-23 14:22 UTC, yufuworks commented
## 発火確認
https://gyazo.com/66d3c1b141907e24ab4ed31b47551830

2019-04-29 08:27 UTC, yufuworks commented
## なぜか画面の初回ロード時に追加を押すと大量に同一アカウントがメンバー追加されることがある
なぜか稀に発生しない。
初回ロードじにajaxが動作しない問題の解決、jsの強制読み込み？処理
$(document).on("turbolinks:load", function(){
の副作用と思われる

2019-04-29 08:31 UTC, yufuworks commented
### [優先度高] アソシエーション先のレコードが保存・更新できない

2019-04-29 13:02 UTC, yufuworks commented
## 確認されている不具合
・新規/編集画面初回ロード直後のインクリメンタルサーチから追加すると複数の同一ユーザーがメンバーリストに作られ、そのままフォーム送信すると同数の同一ユーザーが登録される。このような場合、編集時に全て削除した時のみこの状態を解消できる。

・ボタンの表示が「update」になっているvalue追記でボタンを「更新する」にした場合、ボタンクリックから遷移の間の短い時間「update」表示になってしまう。

2019-04-29 13:21 UTC, yufuworks commented
## 実装動作
↓新規グループ作成時、インクリメンタルサーチ結果からメンバーリストへの追加、削除動作、登録
https://gyazo.com/6ede8c9c3379a4bb8442393e66fba719

2019-04-30 02:04 UTC, miyagit commented on app/controllers/users_controller.rb
> +    @users = User.where('name LIKE(?)', "#{params[:keyword]}%").limit(20)
limitは必要でしょうか？

2019-04-30 03:49 UTC, yufuworks commented on app/controllers/users_controller.rb
> +    @users = User.where('name LIKE(?)', "#{params[:keyword]}%").limit(20)
すいません、今見るとなぜついているのか自分でもわかりませんでした。削除します。

2019-04-30 03:53 UTC, miyagit commented on app/controllers/groups_controller.rb
> +    # params.require(:group).permit(:name, group_users_attributes:[:id])
ここのコメントアウト必要ないならば削除しましょう。

2019-04-30 03:55 UTC, yufuworks commented on app/controllers/groups_controller.rb
> +    # params.require(:group).permit(:name, group_users_attributes:[:id])
こちらは現在特にコメントアウトされた記述はないはずです。

2019-04-30 04:00 UTC, ghost requested changes

2019-04-30 04:00 UTC, ghost commented on app/views/users/index.json.jbuilder
> +end
最後に空行を入れましょう

2019-04-30 04:00 UTC, ghost commented on app/controllers/groups_controller.rb
> +    # params.require(:group).permit(:name, group_users_attributes:[:id])
こちらまだ残っておりますので、ご確認をお願い致します

2019-04-30 04:00 UTC, ghost commented on app/controllers/groups_controller.rb
> +    # @group.group_users.build
こちらも

2019-04-30 04:00 UTC, ghost commented on Gemfile
> +# gem 'trailblazer-rails'
ここら辺も不要なものがあればコメントアウトではなく、削除してください

2019-04-30 04:00 UTC, hiroki5123 commented on Gemfile
> +  repo_name = '#{repo_name}/#{repo_name}' unless repo_name.include?('/')
ここシングルクォーテーションに直すと式展開できなくなると思うのですが、なんでシングルクォーテーションにしてるんでしょうか？

2019-04-30 04:12 UTC, yufuworks commented
groups_controllerのコメントアウトはローカル上では存在しておらず、ブランチの不一致もなかったためスペースで微修正したものをアップデートしました。確認お願いします。

2019-04-30 04:31 UTC, ghost approved these changes
LGTMです！

2019-04-30 04:34 UTC, merged